# Generated by Django 3.2.9 on 2021-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sap',
            field=models.FloatField(default=15),
        ),
    ]
