# Generated by Django 3.2.9 on 2021-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_sap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='sap',
            field=models.IntegerField(default=15),
        ),
    ]
